name: Build and Push Docker Images Azure

on:
  push:
    branches:
      - test/workflows
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  find-and-build:
    runs-on: ubuntu-latest
    environment: test-workflows
    env:
      ACR_REPO: fr0ntierxpublicdev.azurecr.io
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: fr0ntierxpublicdev.azurecr.io
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Find and Build Dockerfiles
        run: |
          # Find all Dockerfiles
          DOCKERFILES=$(find . -name "Dockerfile" -type f)
          echo "Found Dockerfiles: $DOCKERFILES"
          
          # Build and push each Dockerfile
          for file in $DOCKERFILES; do
            SERVICE_DIR=$(dirname "$file")
            SERVICE_NAME=$(basename "$SERVICE_DIR")
            
            echo "📁 Processing $SERVICE_DIR"
            
            # Always create src directory and start.sh
            mkdir -p "$SERVICE_DIR/src"
            cat << 'EOF' > "$SERVICE_DIR/src/start.sh"
            #!/bin/bash
            if [ -f /opt/venv/bin/activate ]; then
              source /opt/venv/bin/activate
            fi
            if command -v ollama &> /dev/null; then
              ollama serve
            else
              python -m vllm.entrypoints.api_server
            fi
            EOF
            chmod +x "$SERVICE_DIR/src/start.sh"
            
            echo "🏗️ Building $SERVICE_NAME from $file"
            
            cd "$SERVICE_DIR"
            docker build -f Dockerfile -t $SERVICE_NAME .
            docker tag $SERVICE_NAME ${{ env.ACR_REPO }}/$SERVICE_NAME:latest
            docker push ${{ env.ACR_REPO }}/$SERVICE_NAME:latest
            cd -
            
            echo "✅ Pushed $SERVICE_NAME"
          done