name: Build and Push Docker Images Azure

on:
  push:
    branches:
      - test/workflows
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  find-and-build:
    runs-on: ubuntu-latest
    env:
      ACR_REPO: fr0ntierxpublicdev.azurecr.io
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: fr0ntierxpublicdev.azurecr.io
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Find and Build Dockerfiles
        run: |
          # Find all Dockerfiles
          DOCKERFILES=$(find . -name "Dockerfile" -type f)
          
          # Build and push each Dockerfile
          for file in $DOCKERFILES; do
            SERVICE_DIR=$(dirname "$file")
            SERVICE_NAME=$(basename "$SERVICE_DIR")
            
            echo "🏗️ Building $SERVICE_NAME from $file"
            
            # Build and tag
            docker build -f "$file" -t $SERVICE_NAME .
            docker tag $SERVICE_NAME ${{ env.ACR_REPO }}/$SERVICE_NAME:latest
            
            # Push
            docker push ${{ env.ACR_REPO }}/$SERVICE_NAME:latest
            
            echo "✅ Pushed $SERVICE_NAME"
          done