name: Build and Push Docker Images Azure

on:
  push:
    branches:
      - test/workflows
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: test-workflows

    env:
      ACR_REPO: fr0ntierxpublicdev.azurecr.io

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Get changed files
        id: files
        run: |
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD | grep Dockerfile || true)
          echo "changes=$CHANGED_FILES" >> $GITHUB_OUTPUT
          echo "Found changed Dockerfiles: $CHANGED_FILES"

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: fr0ntierxpublicdev.azurecr.io
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Build and Push Changed Images
        if: steps.files.outputs.changes != ''
        run: |
          for file in ${{ steps.files.outputs.changes }}; do
            PARENT_DIR=$(dirname $(dirname "$file"))
            TYPE=$(basename $(dirname "$file"))
            SERVICE=$(basename "$PARENT_DIR")
            PROJECT=$(basename $(dirname "$PARENT_DIR"))
            IMAGE_NAME="$PROJECT-$SERVICE-$TYPE"
            
            echo "🏗️ Building $IMAGE_NAME from $file"
            cd $(dirname "$file")
            docker build -f Dockerfile -t $IMAGE_NAME .
            docker tag $IMAGE_NAME ${{ env.ACR_REPO }}/$IMAGE_NAME:latest
            docker push ${{ env.ACR_REPO }}/$IMAGE_NAME:latest
            cd -
            echo "✅ Pushed $IMAGE_NAME"
          done