name: (PRODUCTION) Build and Push Docker Images DockerHub

on:
  pull_request:
    branches:
      - release/prod
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    environment: Docker

    env:
      DOCKERHUB_REPO: fr0ntierx

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get changed files
        id: files
        run: |
          git fetch --prune --unshallow
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            CHANGED=$(find . -name "Dockerfile" | tr '\n' ' ')
          else
            CHANGED=$(git diff --name-only HEAD^ HEAD | grep Dockerfile || true)
          fi
          echo "changes=$CHANGED" >> $GITHUB_OUTPUT
          echo "Found Dockerfiles: $CHANGED"
      - name: Build and Push Changed Images
        if: steps.files.outputs.changes != ''
        run: |
          DOCKERFILES=(${{ steps.files.outputs.changes }})
          
          for file in "${DOCKERFILES[@]}"; do
            PARENT_DIR=$(dirname $(dirname "$file"))
            TYPE=$(basename $(dirname "$file"))
            SERVICE=$(basename "$PARENT_DIR")
            PROJECT=$(basename $(dirname "$PARENT_DIR"))
            IMAGE_NAME="$PROJECT-$SERVICE-$TYPE"
            
            echo "Building $IMAGE_NAME from $file"
            cd $(dirname "$file")
            docker build -f Dockerfile -t $IMAGE_NAME .
            docker tag $IMAGE_NAME ${{ env.DOCKERHUB_REPO }}/$IMAGE_NAME:latest
            docker push ${{ env.DOCKERHUB_REPO }}/$IMAGE_NAME:latest
            cd -
            echo "✅ Pushed $IMAGE_NAME to DockerHub"
          done