name: (PRODUCTION) Build and Push Docker Image DockerHub

on:
  push:
    branches:
      - release/prod
    paths:
      - src/**
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: Docker

    permissions:
      id-token: write
      contents: read

    env:
      IMAGE_NAME: polaris-proxy
      DOCKERHUB_REPO: fr0ntierx/polaris-proxy

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME .

      - name: Tag image for DockerHub
        run: |
          docker tag $IMAGE_NAME $DOCKERHUB_REPO:latest

      - name: Push image to DockerHub
        run: |
          docker push $DOCKERHUB_REPO:latest
