name: (PRODUCTION) Build and Push Docker Image Azure

on:
  push:
    branches:
      - release/prod
    paths:
      - src/**
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: Docker

    permissions:
      id-token: write
      contents: read

    env:
      IMAGE_NAME: polaris-proxy
      ACR_REPO: fr0ntierxpublic.azurecr.io/polaris-proxy

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: fr0ntierxpublic.azurecr.io
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME .

      - name: Tag image for Azure Container Registry
        run: |
          docker tag $IMAGE_NAME $ACR_REPO:latest

      - name: Push image to Azure Container Registry
        run: |
          docker push $ACR_REPO:latest
